import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

// Read the dependency's license text
const depLicensePath = path.resolve("node_modules/diff/LICENSE");
const depLicenseText = fs.readFileSync(depLicensePath, "utf8");

// Wrap it as a block comment
// const bannerComment = `/*!\n${depLicenseText}\n*/`;
const bannerComment = `\n${depLicenseText}\n`;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin


## Third party libraries:

### diff - https://github.com/kpdecker/jsdiff

#### License
${bannerComment}
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: {
    main: "src/main.ts",
    styles: "src/styles.css",
  },
  outdir: ".",
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  legalComments: 'eof',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
